import Image from "next/image"; import Link from "next/link"; import {Navbar} from "@/components/Navbar"; import {EnquiryForm} from "@/components/EnquiryForm";
const services=["Flyers & Posters","Digital Branding","Business Materials","Website Design","Software Development","AI-Powered Solutions"];
const projects=["AmakTech Connect","AmakTech Marketplace","SmartExpense AI","CareerSync AI","EduCore","Personal Portfolio"];
const tech={Frontend:["HTML","CSS","JavaScript","React.js","Next.js","Vite","Tailwind CSS","TypeScript"],Backend:["Node.js","Express.js","Django"],Databases:["PostgreSQL","MySQL","MongoDB","MongoDB Atlas","Firebase"],Application:["JWT","Auth.js","Prisma","Zustand","React Router","Zod"],"Deployment & AI":["Vercel","GitHub","GitHub Pages","AI integrations"]};
export default function Home(){return <><Navbar/><main><section className="hero"><div className="container hero-grid"><div><p className="eyebrow">AMAKTECH SOLUTIONS</p><h1>Transforming <span>Ideas</span> into Digital Solutions.</h1><p className="hero-text">Creative designs, digital branding and professional technology solutions for individuals, businesses, organizations and institutions.</p><div className="hero-actions"><Link href="#contact" className="button button-primary">Start a Project</Link><Link href="#projects" className="button button-secondary">Explore Our Work</Link></div><div className="hero-proof"><strong>Creative Designs.</strong><strong>Digital Solutions.</strong><strong>Professional Results.</strong></div></div><div className="hero-visual"><div className="glow"/><Image src="/logo.png" alt="AmakTech Solutions logo" width={430} height={430} priority className="hero-logo"/><div className="floating-card card-one">Creative + Technology</div><div className="floating-card card-two">Built for growth</div></div></div></section>
<section id="about" className="section"><div className="container split"><div><p className="eyebrow">WHO WE ARE</p><h2>Technology and creativity working together.</h2></div><div><p>AmakTech Solutions is a technology and creative services company providing professional graphic design, digital branding, business design materials, software development and technology solutions.</p><p>Our mission is to provide innovative, professional and accessible solutions that help individuals, businesses and organizations build strong brands, communicate effectively and grow.</p></div></div></section>
<section id="services" className="section section-dark"><div className="container"><div className="section-heading"><div><p className="eyebrow">WHAT WE DO</p><h2>Solutions built around your goals.</h2></div><p>From a single promotional graphic to a complete digital product, we combine creativity with technology.</p></div><div className="service-grid">{services.map((s,i)=><article className="service-card" key={s}><span>0{i+1}</span><h3>{s}</h3><p>Professional, practical and brand-focused solutions designed around your requirements.</p><Link href="#contact">Request service →</Link></article>)}</div></div></section>
<section id="projects" className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">OUR PRODUCTS & PROJECTS</p><h2>Ideas we are turning into digital products.</h2></div></div><div className="project-grid">{projects.map((p,i)=><article className="project-card" key={p}><div className="project-number">0{i+1}</div><p className="project-category">Digital product</p><h3>{p}</h3><p>A growing AmakTech technology initiative demonstrating practical digital product development.</p><Link href="#contact">Discuss project →</Link></article>)}</div></div></section>
<section id="technologies" className="section section-soft"><div className="container"><p className="eyebrow">TECHNOLOGY</p><h2>Modern tools for modern solutions.</h2><div className="tech-grid">{Object.entries(tech).map(([g,items])=><div className="tech-group" key={g}><h3>{g}</h3><div className="tech-list">{items.map(x=><span key={x}>{x}</span>)}</div></div>)}</div></div></section>
<section className="section founder"><div className="container founder-grid"><div className="founder-mark">AM</div><div><p className="eyebrow">FOUNDER</p><h2>Alfred Makura</h2><p className="founder-role">Founder · Frontend Developer · Growing Full-Stack Software Engineer</p><p>Software Engineering graduate with ALX frontend specialization and frontend development training through Chris DesignX Academy, with laboratory technician/lab assistant experience.</p></div></div></section>
<section id="contact" className="section contact-section"><div className="container contact-grid"><div><p className="eyebrow">LET'S BUILD</p><h2>Have an idea? Let's turn it into something real.</h2><p>Tell us what you need. We will review your requirements and get back to you.</p><div className="contact-details"><p><strong>Call:</strong> +263 716 997 735 / +263 782 683 072</p><p><strong>WhatsApp:</strong> +263 716 997 735</p><p><strong>Email:</strong> amaktechsolution@gmail.com</p></div><a className="button button-whatsapp" href="https://wa.me/263716997735" target="_blank" rel="noreferrer">Chat on WhatsApp</a></div><EnquiryForm/></div></section></main><footer className="footer"><div className="container footer-grid"><div><Image src="/logo.png" alt="AmakTech Solutions" width={85} height={85}/><p>Creative Designs. Digital Solutions. Professional Results.</p></div><div><h4>Company</h4><Link href="#about">About</Link><Link href="#services">Services</Link><Link href="#projects">Projects</Link></div><div><h4>Connect</h4><Link href="#contact">Contact</Link><a href="https://www.facebook.com/me/" target="_blank">Facebook</a><a href="https://www.linkedin.com/in/alfred-makura-9b16a4208/" target="_blank">LinkedIn</a></div></div><div className="container footer-bottom">© {new Date().getFullYear()} AmakTech Solutions. All rights reserved.</div></footer></>}
